/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedShopsShopIdRouteImport } from './routes/_authenticated.shops.$shopId'
import { Route as AuthenticatedShopsShopIdIndexRouteImport } from './routes/_authenticated.shops.$shopId.index'
import { Route as AuthenticatedShopsShopIdCustomersRouteImport } from './routes/_authenticated.shops.$shopId.customers'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShopsShopIdRoute =
  AuthenticatedShopsShopIdRouteImport.update({
    id: '/shops/$shopId',
    path: '/shops/$shopId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedShopsShopIdIndexRoute =
  AuthenticatedShopsShopIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedShopsShopIdRoute,
  } as any)
const AuthenticatedShopsShopIdCustomersRoute =
  AuthenticatedShopsShopIdCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedShopsShopIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/shops/$shopId': typeof AuthenticatedShopsShopIdRouteWithChildren
  '/shops/$shopId/customers': typeof AuthenticatedShopsShopIdCustomersRoute
  '/shops/$shopId/': typeof AuthenticatedShopsShopIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/shops/$shopId/customers': typeof AuthenticatedShopsShopIdCustomersRoute
  '/shops/$shopId': typeof AuthenticatedShopsShopIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/shops/$shopId': typeof AuthenticatedShopsShopIdRouteWithChildren
  '/_authenticated/shops/$shopId/customers': typeof AuthenticatedShopsShopIdCustomersRoute
  '/_authenticated/shops/$shopId/': typeof AuthenticatedShopsShopIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/shops/$shopId'
    | '/shops/$shopId/customers'
    | '/shops/$shopId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/shops/$shopId/customers' | '/shops/$shopId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/_authenticated/shops/$shopId'
    | '/_authenticated/shops/$shopId/customers'
    | '/_authenticated/shops/$shopId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shops/$shopId': {
      id: '/_authenticated/shops/$shopId'
      path: '/shops/$shopId'
      fullPath: '/shops/$shopId'
      preLoaderRoute: typeof AuthenticatedShopsShopIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shops/$shopId/': {
      id: '/_authenticated/shops/$shopId/'
      path: '/'
      fullPath: '/shops/$shopId/'
      preLoaderRoute: typeof AuthenticatedShopsShopIdIndexRouteImport
      parentRoute: typeof AuthenticatedShopsShopIdRoute
    }
    '/_authenticated/shops/$shopId/customers': {
      id: '/_authenticated/shops/$shopId/customers'
      path: '/customers'
      fullPath: '/shops/$shopId/customers'
      preLoaderRoute: typeof AuthenticatedShopsShopIdCustomersRouteImport
      parentRoute: typeof AuthenticatedShopsShopIdRoute
    }
  }
}

interface AuthenticatedShopsShopIdRouteChildren {
  AuthenticatedShopsShopIdCustomersRoute: typeof AuthenticatedShopsShopIdCustomersRoute
  AuthenticatedShopsShopIdIndexRoute: typeof AuthenticatedShopsShopIdIndexRoute
}

const AuthenticatedShopsShopIdRouteChildren: AuthenticatedShopsShopIdRouteChildren =
  {
    AuthenticatedShopsShopIdCustomersRoute:
      AuthenticatedShopsShopIdCustomersRoute,
    AuthenticatedShopsShopIdIndexRoute: AuthenticatedShopsShopIdIndexRoute,
  }

const AuthenticatedShopsShopIdRouteWithChildren =
  AuthenticatedShopsShopIdRoute._addFileChildren(
    AuthenticatedShopsShopIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedShopsShopIdRoute: typeof AuthenticatedShopsShopIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedShopsShopIdRoute: AuthenticatedShopsShopIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
